#Hugo configuration
title = "asdf"
baseURL = "https:\/\/asdf.sadf.sfda"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "sadf.sfda"
